### ISSUE TITLE
Tidy data: teach with inflammation, or with DataCarpentry?

### ISSUE THREAD

**Issue by katrinleinweber** [TIBHannover/FAIR-R#3]
We need to add one episode about tidy(ing) data and packaging it up as well. In about half an hour, I got the inflammation data tidied up OK like this:

```{r}
patients <- paste("patient", sep="_", seq(60))
dat <- cbind(dat, patients)
dat_m <- reshape2::melt(data = dat, id.vars = "patients", value.name = "score")
...
usethis::use_data(dat_m)
```

This would fit into the lesson's topic well, but might not be the best teaching material.

@mkuzak & @lwjohnst86: Have you taught DC's [R-eco…dplyr](http://www.datacarpentry.org/R-ecology-lesson/03-dplyr.html) or [r-social…tidyr](http://www.datacarpentry.org/r-socialsci/03-dplyr-tidyr/) episodes? If yes, can you teach one of those again, and I prepare a little bit about `usethis::use_data()` after that episode?

**Comment by lwjohnst86** [comment]
I have not taught those specific lessons, but I have taught dplyr and tidyr many many times. So yes, I could teach one of those again :)

**Comment by katrinleinweber** [comment]
What do you think of https://github.com/TIBHannover/FAIR-R/pull/5/files? I'm adding more context in the conversation there.

**Comment by katrinleinweber** [comment]
Related to #6.
